### PR TITLE
Introduce a Requires delegate in order to express prerequisites (Support for #321)

### PR DESCRIPTION
**Pull request by salfab**
Introduce a Requires delegate in order to express prerequisites that need to be performed before each Assert, and after the Act

The delegate will typically contain assertions that can be performed within the scope of a unit test.
This will be mostly useful to assert before all tests in a context that the no exceptions were thrown.
Requires delegates can be declared in parent classes when using inheritance in order to apply it to a large number of tests.
In that case, however, the delegates must be declared public.

_Sorry for the absence of tests._
I would **love** to write unit tests for this development, however, for some reason, I can't seem to compile any of the unit tests in this solution: no symbols coming from MSpec can be found by the compiler. I barely managed to compile this version by using the command line. 

Surprisingly, using ``build_local`` work, and this is how I managed to produce those changes.

I use Visual Studio Update 3 ans have installed dotnet core 1.1.0

cheers.

### CODE REVIEW

**Comment by salfab** [comment]
Hi @ivanz ,

After a long period of inactivity, I finally fixed the build on my old PR.
Would it be okay to have a look at it and review my contribution ?

Kindly, 

Fabio

**Comment by robertcoltheart** [comment]
As mentioned on the issue, I'm struggling to understand the use case here. Can you provide a sample of how this would be used?

**Comment by salfab** [comment]
> As mentioned on the issue, I'm struggling to understand the use case here. Can you provide a sample of how this would be used?

of course : 

The idea would be to have a ``ContextBase``, inherited by all other contexts.

In this context, there would be a method implementing that delegate, and its role would be to decide which are the tests that expect an exception.

If it does, then the exception is swallowed, and the test will not fail (the normal behavior of MSpec)
If it doesn't expect an exception, then the exception is not swallowed, and it bubbles up until it is caught and displayed by the test runner.

it could be with an attribute, naming convention, or anything else, really.

The following example will show how to only swallow exceptions if the test is known to expect an exception, according to a naming convention.

If the name of the test contains the keyword ``throw``, then exceptions will be handled as usual.

If it doesn't contain the keyword ``throw``, then the Catch.Exception mechanism of MSpec will be overriden, and the exception will show up in the runner.


```csharp
    public class ContextBase
    {
        static ContextBase()
        {
            // ...
        }

        static public Exception ThrownException { get; set; }

        /// <summary>
        /// This pre-requisite will make sure that:
        /// - All tests that do not contain the word "throw"
        /// - And throw an exception
        /// Will fail.
        /// </summary>
        public Requires that_no_unexpected_exceptions_are_thrown = (s) =>
            {
                if (!s.Name.Contains("throw"))
                {
                    if (ThrownException != null)
                    {                        
                        throw new PrerequisiteNotMetException("an exception was thrown - " + ThrownException.GetType() + " - " + ThrownException.Message , ThrownException);
                    };
                }
            };
    }
```

**Comment by robertcoltheart** [comment]
Closing this while we are heavily refactoring. Discussion can continue on #321.

**Pull request closed without merging**
