### PR TITLE
You get a warning regarding ShouldBeOfType

### PR DESCRIPTION
**Pull request by wallymathieu**
In the warning the issue #171 is mentioned.

### CODE REVIEW

**Comment by BrunoJuchli** [comment]
@wallymathieu thank you, i've integrated the PR.

@machine/team-machine 
i'm not sure what the current process is and who is deemed "responsible" for this project. As this was a trivial change and i deemed it a sensible one i've merged this into master.
Please tell me if you mind or if you have directions on how to handle PRs

Thank you all for contributing to open source :-)

**Comment by NameOfTheDragon** [comment]
I’m currently trying to find out who is at the helm. MSpec is too good to let it fade into obscurity and while I can’t dedicate much (or any) time to contributing code, I would be more than happy to take on the role of ‘benevolent dictator’ if that is needed to keep the project alive.

Best regards,
Tim Long

**Comment by jfellien** [comment]
@NameOfTheDragon ‘benevolent dictator’ sounds good, but mostly I have problems with dictators ;-)

@machine/team-machine currently I'm only the contributor of mspec-light. But it seems so @danielmarbach  thougth I'll take the helm. Oh no.. this ist not my intention. MSpec is a community driven project which is in the near of ending, I guess. So if we don't want that MSpec dies, we have to reorganize us.

Any Ideas @all?

**Comment by BrunoJuchli** [comment]
I'm planning on starting to work on my own BDD/ATDD tool in the near future.
Why? Because i have some long-standing issues with mspec like not being able to access "this" and forcing me to use static variables all over (==> driver for test leakage). I want to have a spec-test suite which allows me to write code "naturally" = meaning by applying all the same "rules"  and "guidelines" as i do when implementing "productive" code.
I'm planning to base it on xunit 2.0 (extensible test discovery!) (R# runner is currently lacking and i'm trying to get into contact with matt to see how i can help with that). 
That should cut down implementation work and maintenance drastically as i won't have to maintain all the runner infrastructure.

If mspec wants to stay alive then it might be an option to use xunit 2.0 test discovery /-runners as well.

**Comment by danielmarbach** [comment]
Bruno I tried that. The xunit discovery model makes assumptions about the things you can reflect on. Those assumptions are baked into the framework. You'd have to tweak redo a significant amount of code to achieve this

And by the way I also spiked a convention driven approach based on mspec which would work with xunit 2.0. if you need more details ping me

**Comment by BrunoJuchli** [comment]
@danielmarbach 
yeah i read your blog post a while ago and i think we had a short discussion about it, too. If you've got more information than present in the blog then i'm very happy to hear about it :-)

One can modify xunit 2.0 test discovery by placing an assembly-attribute on the test assembly.
Downside: makes xunit 2.0 and "mspec" (or whatever else) tests coexisting in the same assembly complicated. I've made a note to upload my spike to github.

Currently the xunit resharper runner supports running xunit 2.0 tests but it's still based on xunit 1 test-discovery so the assembly-attribute is not taken into consideration. The console runner though works.

**Comment by NameOfTheDragon** [comment]
It’s a popular governance model, all the best OSS projects are doing it these days… ;-)
http://oss-watch.ac.uk/resources/benevolentdictatorgovernancemodel

Best regards,
Tim Long

**Comment by drauch** [comment]
@BrunoJuchli : Are you sure about writing another framework? I personally don't think one-more-framework is going to solve all our problems. If you are interested in overcoming the downsides of MSpec and/or providing R# support for an existing framework get in contact with https://github.com/matkoch/TestFx . TestFx is two things: a test framework on which you can specify your own DSL while having out-of-the-box R# / TeamCity / etc. support + a sample DSL which overcomes MSpec's "static problem" (which is imo a *huge* downside in some situations).

I'd love to see MSpec living on, so I'm PRO Tim Long for ‘benevolent dictator’. Let's try. If it doesn't work out it can't possible be any worse than the current situation. Although I'm not sure that some dictator without time for design/coding/reviews is going to have much impact in the long run.

BR D.R.

**Comment by DerAlbertCom** [comment]
@danielmarbach with the new expression body functions and properties it maybe a good enough syntax possible, NUnit.Specifications does not work in NUnit 3, because they changed the behavior of there api. but this is all off topic here in that issue ;)

**Comment by drauch** [comment]
I tried some new styles with the new C# method expressions in a very simple test framework, however, it is not enough. No void expressions allowed, too much bloat. Unfortunately no new possibilities.

**Comment by matkoch** [comment]
Can't help myself, but I really need to address this again:

https://github.com/machine/machine.specifications/issues/286

**Pull request merged**
