### PR TITLE
Add test case filter to RunOptions (Support for #327)

### PR DESCRIPTION
**Pull request by MattRyan**
Add constructor overloads to RunOptions to take a ContextFilter instead of a string. ContextFilters class consists of a name property and a set of SpecificationFilters. A SpecificationFilter contain just a name property. ContextFilters without any SpecificationFilters will behave the same as the current string filters. When any SpecificationFilters exist only the specifications with a matching name in that context will be run.

### CODE REVIEW

**Comment by robertcoltheart** [comment]
The change of type for `Filters` isn't going to play nicely with the `Runner.Utility` which relies on this being a string. I need to think about this more carefully.

**Comment by mikeblakeuk** [comment]
@robertcoltheart is there any news on support for vstest.console.exe Filters supporting the Tag attribute?

**Comment by robertcoltheart** [comment]
Now that we've hit version 1.0, we're looking at refactoring and cleaning up a lot of the codebase. Tag support in the console runner will likely be a 2.0 feature.

**Comment by robertcoltheart** [comment]
Closing this while we refactor, tracked in #327

**Pull request closed without merging**
