### PR TITLE
Default namespace for JetBrains annotation attributes

### PR DESCRIPTION
**Pull request by ulrichb**
Implements #282

### CODE REVIEW

**Comment by agross** [comment]
:+1:

**Comment by ulrichb** [comment]
@ivanz Why did you close this PR?

**Comment by ivanz** [comment]
Given that I have not provided a reason it must have been by mistake. Sorry about that. I am on holiday and the reopen button is greyed out on my phone, but if you can - please go ahead and reopen.

**Comment by ulrichb** [comment]
Np. Unfortunately, I have no commit privileges in this repo. Would you review and merge it when I rebase it to the current master?

**Comment by ulrichb** [comment]
I've rebased my branch on the current master. Please re-open to see the changed commit. Further I've added two TODOs in the PR description (see above).

**Comment by ivanz** [comment]
Hi, please open a new pull request from the same branch, because I can't re-open this one.

**Comment by ulrichb** [comment]
@ivanz => #316

**Pull request closed without merging**
